EPS-Libraries-Berkeley/volt

- Search/Searching_for_articles.ipynb
- _toc.yml
Adding Search file and testing process for instructions.
> Adding Search file

- Research_Workflows/Introduction_Research_Workflows.ipynb
- references.bib
Adding references.bib and editing citation.
> Adding Bibliography

- _toc.yml
> Updating toc to include bibliography

- References.ipynb
- _toc.yml
Adding References page to create bibliography.
> Adding References page

- Research_Workflows/Finding_articles.ipynb
- _toc.yml
> test upload Finding_articles and toc

- Research_Workflows/Introduction_Research_Workflows.ipynb
- Search/Searching_for_articles.ipynb
- _toc.yml
- references.bib
- zreferences.md
> Troubleshooting Bibliography

- _toc.yml
> forgot to update toc

- Research_Workflows/Finding_articles.ipynb
- Search/APIs.ipynb
> trying to get book to update

- Search/Search.ipynb
- _toc.yml
Still troubleshooting book build. Moved out some half-written problem files.
> moved problem files

- LaTeX/Equations_and_Formulas.ipynb
- _toc.yml
> Adding test Equations and Formulas file

- Search/exploring_article_databases.ipynb
- _toc.yml
Adding page within Search chapter for database exercise.
> adding database exercise

- Research_Workflows/Finding_articles.ipynb
> testing new content

- requirements.txt
Editing requirements.txt file to try to get arxiv api page to render.
> updating requirements.txt

- _config.yml
editing config file to not execute crossref page
> troubleshooting config

- Introduction/Welcome.ipynb
Added additional text to the welcome page
> Update welcome message

- Organizing/Reference_Management_and_Citations.ipynb
TOC update and adding Organizing chapter
> toc update

- LaTeX/Equations_and_Formulas.ipynb
Added first section of Equations and Formulas
> Updated page

- _toc.yml
> Updated TOC

- _config.yml
Trying to figure out why TOC sidebar is messed up.
> fixing config

- _config.yml
playing with config file to fix toc outline
> outline issues

- Welcome.ipynb
> Add image to welcome

- Organizing/Data_Management.ipynb
minor edit on Data Management page to troubleshoot build error.
> troubleshooting build error

- _toc.yml
updating toc to reflect chapter/part designation, deleted "headers"
> updating toc

- _toc.yml
> removing stray tab in toc

- _toc.yml
Still troubleshooting TOC. Added chapter and part designation back.
> chapter and part added back to toc

- _toc.yml
removing chapters & parts for now
> removing chapters

- _toc.yml
> chapters added back

- LaTeX/Basics.ipynb
- LaTeX/Intro_to_LaTeX.ipynb
- Search/arxiv_api.ipynb
- Search/crossref_library_module.ipynb
- _toc.yml
taking out numbering from api files, updated latex intro.
> small formatting edits

- Welcome.md
added text and images to file, will upload images next
> add welcome images

- Search/arxiv_api.ipynb
fixing header issues in arxiv api page
> header issues

- Introduction/references.bib
correcting couple of errors in .bib file.
> correcting bib file

- Introduction/research_workflows.md
Internet went out during last merge.
> internet glitch

- Introduction/research_workflows.md
Seemed like figures were fine but now they're not. Troubleshooting.
> issues with figures

- Introduction/research_workflows.md
had omitted --- in figure block!
> added missed dashes

- Special_Topics/digital-mapping.md
Updated digital mapping page to fix header issue
> Updated digital mapping page (again)

- Archiving_and_Sharing/Data.ipynb
- Archiving_and_Sharing/Resources.ipynb
- _toc.yml
renamed file to troubleshoot toc sidebar
> troubleshooting toc sidebar

- Organizing/Reference_Management_and_Citations.ipynb
- _toc.yml
update reference & citation management page; update TOC
> update reference page and toc

- _toc.yml
Reverts EPS-Libraries-Berkeley/volt#114
> Revert "As branch"

- LaTeX/Basics.ipynb
Updated LaTeX Basics exercise and added link to solutions
> Updated file

- _config.yml
> incorrect binder url

- Introduction/eps_libraries.md
> image alignment

- Search/searching_for_resources.ipynb
This is an edit to the search.
> edit to search page

- _toc.yml
Try to update TOC to comply with new jupyter book TOC structure
> toc migration

- _toc.yml
> toc migration forgot colon

- Search/crossref_library_module.ipynb
added tag so that code output doesn't show
> changed code output

- Special_Topics/digital-mapping.md
made a slight edit to the end of text
> slight edit

- LaTeX/Equations_and_Formulas.ipynb
Changed a word in the Simple Operators section to make things clearer
> Updated typo on page

- Welcome.md
moved question box from sidebar to margin for better spacing and visibility
> moved question box to margin

- Introduction/eps_libraries.md
EPS Libraries file not showing up in lefthand TOC. Troubleshooting.
> troubleshooting intro file

- LaTeX/latex_workshop.ipynb
- _toc.yml
> updates to latex workshop

- Data/What_is_a_repository.ipynb
removed the list of attributes for a trustworthy repository and setup page to embed pdf
> removed some text to make room for zenodo pdf

- _toc.yml
error in toc - won't add numbering for now.
> fixed toc numbering

- Data/What_is_a_repository.ipynb
switched the pdf embed from our repo to google drive.
> fixing pdf embed

- Reproducibility/zenodo.md
> Bq chapters

- Organizing/Reference_Management_and_Citations.ipynb
Tutorial update - fingers crossed
> Lngobranch

- Organizing/Reference_Management_and_Citations.ipynb
changed embed code for zotero tutorial
> embedtutorial test

- Bibliography.md
- Introduction/research_workflows.md
- _config.yml
- _toc.yml
- references.bib
I don't think this is a complete fix, but now we have a bibliography for the whole book.
> trying to fix bibliography

- Introduction/research_workflows.md
can't get all of the citation styles to work, but the basic {cite} one does.
> fixing citation notation

- Introduction/eps_libraries.md
small edit to update leconte to physics change, and test new github installation
> update physics location

- Search/dissertations.ipynb
> adding page about dissertation searching

- Search/dissertations.md
removed extra dissertations file
> removed extra file

- Welcome.md
trying to get the question widget to display correctly in the margin
> question widget display

- LaTeX/latex_workshop.ipynb
- Welcome.md
- _config.yml
Switching vOLT to VOLT
Update to LaTeX workshop
> volt acronym and latex update

- LaTeX/Tables.ipynb
spotted a few errors on the new Tables page
> fixing errors

- Welcome.md
removed old group photo
changed division to Sciences
updated staff list
> staff page update
